name: '🔏 Yarn Lock Changes'
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: '🚚 Checkout'
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: '🔏 Yarn Lock Changes'
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
