name: '🧪 Run Tests'
on: [pull_request]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24]
    name: Testing on Node ${{ matrix.node }}
    steps:
      - name: '🚚 Checkout'
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: '🔧 Setup Node'
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ matrix.node }}
      - name: '📦️ Install dependencies'
        run: yarn
      - name: '🧪 Run Unit tests'
        run: yarn test
      - name: '⚗️ Run CI Classic test'
        uses: ./
        with:
          path: tests/ci/classic/yarn.lock
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: '⚗️ Run CI Berry v2 test'
        uses: ./
        with:
          path: tests/ci/berry-v2/yarn.lock
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: '⚗️ Run CI Berry v3 test'
        uses: ./
        with:
          path: tests/ci/berry-v3/yarn.lock
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: '⚗️ Run CI Berry v4 test'
        uses: ./
        with:
          path: tests/ci/berry-v4/yarn.lock
          token: ${{ secrets.GITHUB_TOKEN }}
